---
title: "Portfolio-hw"
  pdf_document: default
  word_document: default
  html_document: default
---
```{r}
#In order to set up ETFs portfolios and analyze short-term tail risk, we choose three different portfolios with different industries. For the first portfolio which is pretty diverse, it is included ETFs from 3 industries: Agricultural commodity, Metals and Healthcare, and ETFs from 2 different supporters: government and corporate. 
```

```{r portfolio_1}
library(quantmod)
library(mosaic)
library(foreach)
library(tidyverse)
# Import ETF from different industries and different functions
# Agriculture, metal, healthcare, government, corporate
# pretty safe
set.seed(9)
portfolio_1 = c("LQD", "TAGS", "DBB","SHV","IHI")
getSymbols(portfolio_1, from = "2015-01-01") 

# Adjust for splits and dividends
LQDa = adjustOHLC(LQD)
TAGSa = adjustOHLC(TAGS)
DBBa = adjustOHLC(DBB)
SHVa = adjustOHLC(SHV)
IHIa = adjustOHLC(IHI)
# Look at close-to-close changes
plot(ClCl(DBBa))
title('Close-to-Close Changes for DBB')
set.seed(9)
# Combine close to close changes in a single matrix
all_returns_1 = cbind(ClCl(LQDa),ClCl(TAGSa),ClCl(DBBa),ClCl(SHVa),ClCl(IHIa))
head(all_returns_1)
all_returns_1 = as.matrix(na.omit(all_returns_1))
N = nrow(all_returns_1)

pairs(all_returns_1)
title('Correlationship between ETFs in portfolio 1')

# Look at the portfolio_1 returns over time
plot(all_returns_1[,5], type='l')

# are today's returns correlated with tomorrow's? 
# See today's return and tomorrow's for one ETFs  
plot(all_returns_1[1:(N-1),5], all_returns_1[2:N,5])
title("Today's return vs Tomorrow's return for IHI")

for(ticker in portfolio_1) {
	expr = paste0(ticker, "a = adjustOHLC(", ticker, ")")
	eval(parse(text=expr))
}

head(LQDa)
# Sample a random return from the empirical joint distribution
# This simulates a random day
set.seed(9)
return.today = resample(all_returns_1, 1, orig.ids=FALSE)
initial_wealth = 100000
sim1 = foreach(i=1:50, .combine='rbind') %do% {
	total_wealth = initial_wealth
	weights = c(0.2, 0.2, 0.2, 0.2, 0.2)
	holdings = weights * total_wealth
	n_days = 20
	wealthtracker = rep(0, n_days)
	for(today in 1:n_days) {
		return.today = resample(all_returns_1, 1, orig.ids=FALSE)
		holdings = holdings + holdings*return.today
		total_wealth = sum(holdings)
		wealthtracker[today] = total_wealth
	}
	wealthtracker
}

head(sim1)
hist(sim1[,n_days], 25)
title("Capital Changes for portfolio 2")
# Profit/loss
mean(sim1[,n_days])
hist(sim1[,n_days]- initial_wealth, breaks=30)
title("Returns Or Loss",line=2)
mean(sim1[,n_days] > 100000)
quantile(sim1[,n_days]- initial_wealth,.05)
quantile(sim1[,n_days]- initial_wealth,.01)
```
```{r}
#The mean of capital after 20 trading days is 100708.6 and we can earn an average rate of return of 0.7% for 20 trading days on our investment. In addition, we could earn returns at the 58% confidence. Considering the VaR, if the degree of risk preference and acceptance ability of our investors is 5%, portfolio 1 has a 5% VaR of 3128, which means that there is a 0.05 probability that the portfolio 1 will fall in value by more than 3128 in a 20 trading-day period. If the degree of risk preference and acceptance ability of our investors is 1%, portfolio 1 has a 1% VaR of 4396, which means that there is a 0.01 probability that the portfolio 1 will fall in value by more than 4396 in a 20 trading-day period. 
```
```{r}
# Portfolio 2 is more aggressive. It contains two kinds of bonds, which are volitality and leverage bonds. Leverage bonds provide magnified exposure to popular fixed income benchmarks. They can generage amplified returns and also have higher risks. Volitality ETFs tend to move in the opposite direction of the broad market. Therefore, the portfolio 2 is supposed to win the market and win more when the market is down. However, it has to cover more risks as well whe nthe market is up.
```

```{r portfolio_2}
portfolio_2 = c("VIXY", "VIXM", "VIIX","TBT","TMV")
getSymbols(portfolio_2, from = "2015-01-01") 
set.seed(9)
# Adjust for splits and dividends
VIXYa = adjustOHLC(VIXY)
VIXMa = adjustOHLC(VIXM)
VIIXa = adjustOHLC(TBT)
TMVa = adjustOHLC(TMV)
TBTa = adjustOHLC(TBT)
# Look at close-to-close changes
plot(ClCl(VIXYa))
title('Close-to-Close Changes for VIXY')
set.seed(9)
all_returns_2 = cbind(ClCl(VIXYa),ClCl(VIXMa),ClCl(VIIXa),ClCl(TMVa),ClCl(TBTa))
head(all_returns_2)
all_returns_2 = as.matrix(na.omit(all_returns_2))
N = nrow(all_returns_2)

pairs(all_returns_2)
title('Correlationship between ETFs in portfolio 2')

# Look at the portfolio_2 returns over time
plot(all_returns_2[,5], type='l')

# are today's returns correlated with tomorrow's? 
plot(all_returns_2[1:(N-1),5], all_returns_2[2:N,5])
title("Today's return vs Tomorrow's return for TBT")

for(ticker in portfolio_2) {
	expr = paste0(ticker, "a = adjustOHLC(", ticker, ")")
	eval(parse(text=expr))
}

head(TBTa)
set.seed(9)
# Sample a random return from the empirical joint distribution
# This simulates a random day
return.today = resample(all_returns_2, 1, orig.ids=FALSE)

initial_wealth = 100000
sim2 = foreach(i=1:50, .combine='rbind') %do% {
	total_wealth = initial_wealth
	weights = c(0.2, 0.2, 0.2, 0.2, 0.2)
	holdings = weights * total_wealth
	n_days = 20
	wealthtracker = rep(0, n_days)
	for(today in 1:n_days) {
		return.today = resample(all_returns_2, 1, orig.ids=FALSE)
		holdings = holdings + holdings*return.today
		total_wealth = sum(holdings)
		wealthtracker[today] = total_wealth
	}
	wealthtracker
}

head(sim2)
hist(sim2[,n_days], 25)
title("Capital Changes for portfolio 2",line=2)
# Profit/loss
mean(sim2[,n_days])
hist(sim2[,n_days]-initial_wealth, breaks=30)
title("Returns Or Loss",line=2)
mean(sim2[,n_days] > 100000)
quantile(sim2[,n_days]-initial_wealth,.05)
quantile(sim2[,n_days]-initial_wealth,.01)
```
```{r}
# If we invest portfolio 2, the mean of capital is only 96862 for 20 trading days, which has the 3.1% loss. And there is only 34% probability to win. For investors at 5% of risk preference, the value in risk is more than 15539. For investors at 1% of risk preference, the value in risk is more than 17789. It only earns when the market is down, so we need to pay close attention to the broad market when investing this portfolio. 
```

```{r}
# Finally, we choose a safer portfolio containing 5 government bonds. Government Bonds ETFs offer investors exposure to fixed income securities issued by government agencies, which have little risk and small returns as well. They are more preferred by risk averse individuals.
```

```{r portfolio_3}
portfolio_3 = c("IEF", "SHY", "BIL","GOVT","SCHO")
getSymbols(portfolio_3, from = "2015-01-01") 
# Adjust for splits and dividends
IEFa = adjustOHLC(IEF)
SHYa = adjustOHLC(SHY)
BILa = adjustOHLC(BIL)
GOVTa = adjustOHLC(GOVT)
SCHOa = adjustOHLC(SCHO)
# Look at close-to-close changes
plot(ClCl(SCHOa))
title('Close-to-Close Changes for SCHO')
set.seed(99)

all_returns_3 = cbind(ClCl(IEFa),ClCl(SHYa),ClCl(BILa),ClCl(GOVTa),ClCl(SCHOa))
head(all_returns_3)
all_returns_3 = as.matrix(na.omit(all_returns_3))
N = nrow(all_returns_3)

pairs(all_returns_3)
title('Correlationship between ETFs in portfolio 3')
# all related. Because it is in the same industry
plot(all_returns_3[,1], type='l')
all_returns_3[,5]
# Look at the portfolio_3 returns over time
plot(all_returns_3[,5], type='l')

# are today's returns correlated with tomorrow's? 
plot(all_returns_1[1:(N-1),5], all_returns_1[2:N,5])
title("Today's return vs Tomorrow's return for SCHO")

for(ticker in portfolio_3) {
	expr = paste0(ticker, "a = adjustOHLC(", ticker, ")")
	eval(parse(text=expr))
}


# Sample a random return from the empirical joint distribution
# This simulates a random day
set.seed(99)
return.today = resample(all_returns_3, 1, orig.ids=FALSE)

initial_wealth = 100000
sim3 = foreach(i=1:50, .combine='rbind') %do% {
	total_wealth = initial_wealth
	weights = c(0.2, 0.2, 0.2, 0.2, 0.2)
	holdings = weights * total_wealth
	n_days = 20
	wealthtracker = rep(0, n_days)
	for(today in 1:n_days) {
		return.today = resample(all_returns_3, 1, orig.ids=FALSE)
		holdings = holdings + holdings*return.today
		total_wealth = sum(holdings)
		wealthtracker[today] = total_wealth
	}
	wealthtracker
}

head(sim3)
hist(sim3[,n_days], 25)
title("Capital Changes for portfolio 3")
# Profit/loss
mean(sim3[,n_days])
hist(sim3[,n_days]- initial_wealth, breaks=30)
title("Returns Or Loss",line=2)
mean(sim3[,n_days] > 100000)
quantile(sim3[,n_days]- initial_wealth,.05)
quantile(sim3[,n_days]- initial_wealth,.01)
```
```{r}
# From the return and loss histogram, we know that the portfolio 3 is safer than portfolio 1 and 2, the most loss can only be 1500 and also the most earns can only less than 1200 approximately which follows the principle of low risk and low return. Also the correlationship between ETFs in porfolio 3, they have close relationship between each other since they are all issued by government agencies and varied simultaneously. For investors at 1% of risk preference, the value in risk is more than 1302.
```

```{r}
# Combine VaR for three portfolios
Portfolio_3 <- c(quantile(sim3[,n_days]- initial_wealth,.05), quantile(sim3[,n_days]- initial_wealth,.01))
Portfolio_2 <- c(quantile(sim2[,n_days]- initial_wealth,.05), quantile(sim2[,n_days]- initial_wealth,.01))
Portfolio_1<- c(quantile(sim1[,n_days]- initial_wealth,.05), quantile(sim1[,n_days]- initial_wealth,.01))
VaR <- rbind(Portfolio_1,Portfolio_2,Portfolio_3)
dimnames(VaR) = list( c("Portfolio 1","Portfolio 2","Portfolio 3"),c("5%","1%"))
VaR

barplot(VaR, beside = TRUE,legend=TRUE,col=c("darkblue","grey","orange"),cex.names=0.8,las=1,bty ="n",args.legend = list(x ='bottom', bty='n', inset=c(-0.25,0)))
title("VaR For 3 Portfolio at 5% and 1%")

```
```{r}
# From the VaR at 5% and 1% for these 3 portfolios, we can see that the porfolio 2 loses most and covers the most risks and the porfolio 1 is the safest compared with other porfolios. Also, the value at risk is also different by the lose probability. 1% lose probability will lose more compared with 5% lose probability. And the probability also represents the risk preference of investors. If the investors have low risk preference, it means that we need to consider high lose probability and the VaR turns out to be less. And we need to choose safer portfolio, like portfolio 1 or 2, in order to hedge risk as much as possible.
```

